### ISSUE TITLE
Setup issues when trying to save after selecting list.

### ISSUE THREAD

**Issue by a-am** [ethercreative/mailchimp-commerce#42]
When setting up the plugin we have the api key added.  When we go to select a list we continue to receive this error.

`{"type":"https://mailchimp.com/developer/marketing/docs/errors/","title":"Bad Request","status":400,"detail":"We were unable to process the request. A store with the domain https://*********.org/ and platform Craft Commerce already exists in the account.","instance":"bdd6896f-fc62-486f-8f0e-c440f6945a26"}`.  

Where in Mailchimp is this causing an error, integrations? Or is this a Craft Plugin issue? Is the store referencing something in Craft or Mailchimp?

**Comment by a-am** [comment]
Any Idea on this one, we can't seem to get past the setup and in the Mailchimp CP we are unable to find where to reset the stored domain, as the error is indicating.

**Comment by RitterKnightCreative** [comment]
@a-am  - We actually just went through this with a new client. Turns out they had a store connected years ago but for whatever reason the plugin got disabled/uninstalled, etc.  

 It's also likely you're trying to use another API Key then the one that the store was connected with.

The fix is to disconnect the integration then add it again. MailChimp buries this but it's under Integrations -> Manage.  Then click on "Mange your sites" in the hero at the top. On the next screen hit the "Disconnect" button way at the bottom. When you reconnect with Craft it should then work. (I think you can also get to integrations via Account -> integrations.)

**Comment by a-am** [comment]
@RitterKnightCreative which integration do you select for Craft if you are creating a new one?

**Comment by RitterKnightCreative** [comment]
@a-am Connect it from Craft’s side, MC seems to handle the rest.

**Comment by a-am** [comment]
I contacted Mailchimp Support and they found a phantom store with same details.  They had to clear out the phantom store before the plugin could make any connection.

**Comment by alexjcollins** [comment]
@a-am Thank you for adding that information. Hopefully, it'll help others experiencing the same issue.
